# Generated by Django 5.2.7 on 2025-10-11 20:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_type', 'name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('perfume', 'Парфюмерия'), ('pigment', 'Пигменты')], default='perfume', max_length=20, verbose_name='Тип категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Рекомендуемый'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='category',
            field=models.ForeignKey(limit_choices_to={'category_type': 'perfume'}, on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='Pigment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('color_code', models.CharField(blank=True, max_length=20, verbose_name='Код цвета')),
                ('color_type', models.CharField(choices=[('powder', 'Порошок'), ('liquid', 'Жидкий'), ('paste', 'Паста')], default='powder', max_length=20, verbose_name='Тип цвета')),
                ('application_type', models.CharField(choices=[('cosmetics', 'Косметика'), ('art', 'Искусство'), ('industrial', 'Промышленность'), ('food', 'Пищевая')], default='cosmetics', max_length=20, verbose_name='Применение')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('weight_gr', models.PositiveIntegerField(verbose_name='Вес (г)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pigments/', verbose_name='Изображение')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('featured', models.BooleanField(default=False, verbose_name='Рекомендуемый')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(limit_choices_to={'category_type': 'pigment'}, on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Пигмент',
                'verbose_name_plural': 'Пигменты',
                'ordering': ['-created_at'],
            },
        ),
    ]
