# Generated by Django 5.2.7 on 2025-10-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('cdek', 'CDEK'), ('russian_post', 'Почта России'), ('pickup', 'Самовывоз')], max_length=20, verbose_name='Способ доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_service_order_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID заказа в службе доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ожидаемая дата доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID платежа в платежной системе'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Трекинг-номер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Банковская карта'), ('cash', 'Наличными при получении'), ('transfer', 'Банковский перевод'), ('yookassa', 'ЮKassa'), ('tinkoff', 'Тинькофф')], default='card', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
