# Generated by Django 5.2.7 on 2025-12-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='magic_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Магический токен'),
        ),
    ]
