# Generated by Django 5.2 on 2025-12-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_add_magic_token_to_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='register_data',
            field=models.TextField(blank=True, null=True, verbose_name='Данные регистрации (JSON)'),
        ),
    ]
