# Generated by Django 5.2.7 on 2025-12-08 00:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_loyalty_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='discount_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец акции'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Процент скидки (0-100)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Скидка (%)'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Если указано, используется вместо расчета по проценту', max_digits=10, null=True, verbose_name='Цена со скидкой'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='discount_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало акции'),
        ),
        migrations.AddField(
            model_name='pigment',
            name='discount_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец акции'),
        ),
        migrations.AddField(
            model_name='pigment',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Процент скидки (0-100)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Скидка (%)'),
        ),
        migrations.AddField(
            model_name='pigment',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Если указано, используется вместо расчета по проценту', max_digits=10, null=True, verbose_name='Цена со скидкой'),
        ),
        migrations.AddField(
            model_name='pigment',
            name='discount_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало акции'),
        ),
    ]
