# Generated by Django 5.2.7 on 2025-12-09 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_promotion_id'),
        ('store', '0015_trendingproduct'),
    ]

    operations = [
    ]
