# Generated by Django 5.2.7 on 2025-12-11 22:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_merge_0015_alter_promotion_id_0015_trendingproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='selected_volume_ml',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Выбранный объем (мл)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selected_weight_gr',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Выбранный вес (г)'),
        ),
        migrations.AlterField(
            model_name='trendingproduct',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='VolumeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_ml', models.PositiveIntegerField(verbose_name='Объем (мл)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('discount_percentage', models.PositiveIntegerField(default=0, help_text='Процент скидки (0-100)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Скидка (%)')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text='Если указано, используется вместо расчета по проценту', max_digits=10, null=True, verbose_name='Цена со скидкой')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_options', to='store.perfume', verbose_name='Парфюм')),
            ],
            options={
                'verbose_name': 'Вариант объема',
                'verbose_name_plural': 'Варианты объема',
                'ordering': ['volume_ml'],
                'unique_together': {('perfume', 'volume_ml')},
            },
        ),
        migrations.AddField(
            model_name='cartitem',
            name='volume_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.volumeoption', verbose_name='Выбранный объем'),
        ),
        migrations.CreateModel(
            name='WeightOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_gr', models.PositiveIntegerField(verbose_name='Вес (г)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('discount_percentage', models.PositiveIntegerField(default=0, help_text='Процент скидки (0-100)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Скидка (%)')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text='Если указано, используется вместо расчета по проценту', max_digits=10, null=True, verbose_name='Цена со скидкой')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('pigment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_options', to='store.pigment', verbose_name='Пигмент')),
            ],
            options={
                'verbose_name': 'Вариант веса',
                'verbose_name_plural': 'Варианты веса',
                'ordering': ['weight_gr'],
                'unique_together': {('pigment', 'weight_gr')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='weight_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.weightoption', verbose_name='Выбранный вес'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'perfume', 'pigment', 'volume_option', 'weight_option')},
        ),
    ]
